name: "Home Assistant Samsung the Frame changer"
description: "This addon allows you to change your Samsung Frame's art based on a folder of images on your computer. The script picks an image from folder on your computer, then sends it to your TV and sets it as the active image automatically—it also does its best to try not repeatedly upload the same photo to your TV."
version: "2.4"
url: "https://github.com/janstrm/homeassistant-samsungframe-artmode"
slug: "hass-frame-changer"
init: false
startup: services
boot: manual
stdin: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - "media:rw"
options:
  tv: "192.168.1.1"
  photo_filter: None
  matte: none
  matte_color: black
  ai_art_enabled: false
  ai_art_prompt: "A beautiful landscape painting"
  api_key: ""
  rotation_interval: 15
  ensure_art_mode_only: false
  debug: false
schema:
  tv: "str?"
  photo_filter: list(None|Aqua|ArtDeco|Ink|Wash|Pastel|Feuve)?
  matte: list(none|myshelf|modernthin|modern|modernwide|flexible|shadowbox|panoramic|triptych|mix|squares)?
  matte_color: list(black|neutral|antique|warm|polar|sand|seafoam|sage|burgandy|navy|apricot|byzantine|lavender|redorange|skyblue|turquoise)?
  ai_art_enabled: "bool"
  ai_art_prompt: "str"
  api_key: "password"
  rotation_interval: "int?"
  ensure_art_mode_only: "bool"
  debug: "bool"
# For local builds, you can omit 'image' to build in Supervisor. Uncomment and set if publishing images.
# image: ghcr.io/janstrm/{arch}-addon-homeassistant-samsungframe-artmode
