name: "Home Assistant Samsung Frame Art Director"
description: "This addon allows you to change your Samsung Frame's art based on a folder of images on your computer. The script picks an image from folder on your computer, then sends it to your TV and sets it as the active image automatically—it also does its best to try not repeatedly upload the same photo to your TV."
version: "2.5"
url: "https://github.com/janstrm/Home-Assistant-Samsung-Frame-Director"
slug: "ha-samsung-frame-art-director"
init: false
startup: services
boot: manual
stdin: true
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - "media:rw"
options:
  tv: "192.168.1.1"
  photo_filter: None
  matte: none
  matte_color: black
  rotation_interval: 15
  ensure_art_mode_only: false
  debug: false
  power_state_check: true
  turn_on_art_mode: true
schema:
  tv: "str?"
  photo_filter: list(None|Aqua|ArtDeco|Ink|Wash|Pastel|Feuve)?
  matte: list(none|myshelf|modernthin|modern|modernwide|flexible|shadowbox|panoramic|triptych|mix|squares)?
  matte_color: list(black|neutral|antique|warm|polar|sand|seafoam|sage|burgandy|navy|apricot|byzantine|lavender|redorange|skyblue|turquoise)?
  rotation_interval: "int(min=1)?"
  ensure_art_mode_only: "bool"
  debug: "bool"
  power_state_check: "bool"
  turn_on_art_mode: "bool"
# For local builds, you can omit 'image' to build in Supervisor. Uncomment and set if publishing images.
# image: ghcr.io/janstrm/{arch}-addon-homeassistant-samsung-frame-art-director